from datetime import datetime
from pathlib import Path
from tempfile import NamedTemporaryFile
import re


TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates" / "documents"


def _clean_markdown(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"```(?:markdown)?", "", text)
    text = text.replace("```", "")
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    return text.strip()


def markdown_to_sections(markdown: str) -> list[dict]:
    sections = []
    current = {"heading": "Overview", "body": []}

    for raw_line in _clean_markdown(markdown).splitlines():
        line = raw_line.strip()
        if not line:
            continue

        heading_match = re.match(r"^#{1,3}\s+(.+)$", line)
        if heading_match:
            if current["body"]:
                sections.append(
                    {"heading": current["heading"], "body": "\n".join(current["body"])}
                )
            current = {"heading": heading_match.group(1).strip(), "body": []}
            continue

        numbered_heading = re.match(r"^\d+[\).\s-]+([A-Z][A-Za-z0-9 ,/&:-]{3,})$", line)
        if numbered_heading and len(line) < 90:
            if current["body"]:
                sections.append(
                    {"heading": current["heading"], "body": "\n".join(current["body"])}
                )
            current = {"heading": numbered_heading.group(1).strip(), "body": []}
            continue

        if line.startswith(("- ", "* ")):
            line = f"- {line[2:].strip()}"

        current["body"].append(line)

    if current["body"]:
        sections.append({"heading": current["heading"], "body": "\n".join(current["body"])})

    return sections or [{"heading": "Overview", "body": _clean_markdown(markdown)}]


def _ensure_template(template_name: str) -> Path:
    TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)
    template_path = TEMPLATE_DIR / template_name
    if template_path.exists():
        return template_path

    from docx import Document
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Inches, Pt, RGBColor

    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    styles = doc.styles
    styles["Normal"].font.name = "Inter"
    styles["Normal"].font.size = Pt(10.5)
    styles["Title"].font.name = "Inter"
    styles["Title"].font.size = Pt(24)
    styles["Title"].font.bold = True
    styles["Heading 1"].font.name = "Inter"
    styles["Heading 1"].font.size = Pt(15)
    styles["Heading 1"].font.bold = True
    styles["Heading 1"].font.color.rgb = RGBColor(26, 28, 41)

    cover = doc.add_paragraph()
    cover.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = cover.add_run("{{ title }}")
    title_run.bold = True
    title_run.font.size = Pt(26)
    title_run.font.color.rgb = RGBColor(26, 28, 41)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.add_run("{{ document_type }} generated by Clariva").font.size = Pt(11)

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run("Generated {{ generated_date }}").font.size = Pt(9)

    doc.add_paragraph("")
    doc.add_paragraph("{% for section in sections %}")
    doc.add_paragraph("{{ section.heading }}", style="Heading 1")
    doc.add_paragraph("{{ section.body }}")
    doc.add_paragraph("{% endfor %}")

    doc.save(template_path)
    return template_path


def render_docx_from_markdown(
    *,
    markdown: str,
    title: str,
    document_type: str,
    template_name: str | None = None,
) -> str:
    from docxtpl import DocxTemplate

    selected_template = template_name or f"{document_type.lower()}_template.docx"
    template_path = _ensure_template(selected_template)
    doc = DocxTemplate(str(template_path))
    context = {
        "title": title,
        "document_type": document_type,
        "generated_date": datetime.utcnow().strftime("%B %d, %Y"),
        "sections": markdown_to_sections(markdown),
    }
    doc.render(context)

    output = NamedTemporaryFile(delete=False, suffix=".docx")
    output.close()
    doc.save(output.name)
    return output.name
