services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clariva-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
