import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import Logo from '../Logo';
import '../index.css';

const TermsPage = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="policy-container">
      <nav className="navbar">
        <div className="nav-brand">
          <Link to="/"><Logo style={{ width: '140px', height: 'auto' }} /></Link>
        </div>
        <div className="nav-links">
          <Link to="/" className="nav-item">Back to Home</Link>
        </div>
      </nav>

      <main className="policy-content">
        <h1>Terms of Service</h1>
        <p className="last-updated">Last Updated: May 9, 2026</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using Clariva (clarivaai.tech), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.</p>
        </section>

        <section>
          <h2>2. Use License</h2>
          <p>Clariva provides AI-powered document generation. You are granted a limited license to use the generated content for your business or personal projects. However, you may not:</p>
          <ul>
            <li>Use the service for any illegal or unauthorized purpose.</li>
            <li>Attempt to decompile or reverse engineer any software contained on Clariva's website.</li>
            <li>Use the service to generate harmful, offensive, or misleading content.</li>
          </ul>
        </section>

        <section>
          <h2>3. User Accounts</h2>
          <p>When you create an account with us, you must provide information that is accurate and complete. You are responsible for safeguarding the password that you use to access the service and for any activities or actions under your password.</p>
        </section>

        <section>
          <h2>4. Credits and Payments</h2>
          <p>Clariva uses a credit-based system. Credits are refilled automatically based on your plan. We reserve the right to modify credit limits or introduce paid tiers in the future. All fees are non-refundable unless required by law.</p>
        </section>

        <section>
          <h2>5. Intellectual Property</h2>
          <p>The service and its original content, features, and functionality are and will remain the exclusive property of Clariva and its licensors. The generated documents (SOWs, PRDs) are yours to use, but the underlying AI models and platform code belong to us.</p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>In no event shall Clariva, nor its directors, employees, or partners, be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service or the accuracy of the documents generated by the AI.</p>
        </section>

        <section>
          <h2>7. Disclaimer</h2>
          <p>The materials on Clariva's website are provided on an 'as is' basis. Clariva makes no warranties, expressed or implied, and hereby disclaims all other warranties including, without limitation, implied warranties or conditions of merchantability or fitness for a particular purpose.</p>
        </section>

        <section>
          <h2>8. Governing Law</h2>
          <p>These terms and conditions are governed by and construed in accordance with the laws of your jurisdiction, and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>
        </section>

        <section>
          <h2>9. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at support@clarivaai.tech.</p>
        </section>
      </main>

      <footer className="footer" style={{ marginTop: '60px' }}>
        <p>&copy; 2026 Clariva. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default TermsPage;
